# Description: Configuration file for data

# Zenodo record for datasets
record: 17661273
# Filename for PCHiC data
PCHiC_filename: "PCHiC_peak_matrix_cutoff5.tsv"

# General parameters
resources:
  cores: 20
  mem_mb: 400000

# Dataset specific parameters
smallpbmc:
  organism: 'hg38'
pbmc10x:
  organism: 'hg38'
celllines:
  organism: 'hg38'
bmmcneurips:
  organism: 'hg38'

